env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb-base
  - airbnb-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json" 
plugins:
  - react
  - prettier
rules: { "prettier/prettier": "error" }
